#############################################################################
# Makefile for building: treeqt
# Generated by qmake (2.01a) (Qt 4.6.2) on: Sun Sep 5 23:31:18 2010
# Project:  treeqt.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile treeqt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSvg -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MemSvgWidget.cpp \
		node.cpp \
		svgwindow.cpp moc_MemSvgWidget.cpp \
		moc_svgwindow.cpp
OBJECTS       = main.o \
		MemSvgWidget.o \
		node.o \
		svgwindow.o \
		moc_MemSvgWidget.o \
		moc_svgwindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		treeqt.pro
QMAKE_TARGET  = treeqt
DESTDIR       = 
TARGET        = treeqt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: treeqt.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSvg.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile treeqt.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSvg.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile treeqt.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/treeqt1.0.0 || $(MKDIR) .tmp/treeqt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/treeqt1.0.0/ && $(COPY_FILE) --parents MemSvgWidget.hpp node.hpp svgwindow.hpp ui_treeqt.h .tmp/treeqt1.0.0/ && $(COPY_FILE) --parents main.cpp MemSvgWidget.cpp node.cpp svgwindow.cpp .tmp/treeqt1.0.0/ && (cd `dirname .tmp/treeqt1.0.0` && $(TAR) treeqt1.0.0.tar treeqt1.0.0 && $(COMPRESS) treeqt1.0.0.tar) && $(MOVE) `dirname .tmp/treeqt1.0.0`/treeqt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/treeqt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MemSvgWidget.cpp moc_svgwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MemSvgWidget.cpp moc_svgwindow.cpp
moc_MemSvgWidget.cpp: MemSvgWidget.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MemSvgWidget.hpp -o moc_MemSvgWidget.cpp

moc_svgwindow.cpp: svgwindow.hpp
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) svgwindow.hpp -o moc_svgwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp node.hpp \
		svgwindow.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MemSvgWidget.o: MemSvgWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MemSvgWidget.o MemSvgWidget.cpp

node.o: node.cpp node.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

svgwindow.o: svgwindow.cpp node.hpp \
		svgwindow.hpp \
		MemSvgWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o svgwindow.o svgwindow.cpp

moc_MemSvgWidget.o: moc_MemSvgWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MemSvgWidget.o moc_MemSvgWidget.cpp

moc_svgwindow.o: moc_svgwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_svgwindow.o moc_svgwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

