######################################################################
# Automatically generated by qmake (1.07a) Tue Aug 24 23:21:39 2010
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += tree.hpp
SOURCES += main.cpp node.cpp
