######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 2 00:13:09 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tree.hpp
FORMS += treeqt.ui
SOURCES += main.cpp node.cpp

QT += svg
