######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 5 23:30:13 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MemSvgWidget.hpp node.hpp svgwindow.hpp ui_treeqt.h
SOURCES += main.cpp MemSvgWidget.cpp node.cpp svgwindow.cpp
QT += svg
